--liquibase formatted sql
--changeset architect:20250826_add_timestamps
--comment: Add timestamp fields to all entities

ALTER TABLE BOARDS ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE BOARDS ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE BOARDS_COLUMNS ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE BOARDS_COLUMNS ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE CARDS ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE CARDS ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

--rollback ALTER TABLE BOARDS DROP COLUMN created_at, DROP COLUMN updated_at;
--rollback ALTER TABLE BOARDS_COLUMNS DROP COLUMN created_at, DROP COLUMN updated_at;
--rollback ALTER TABLE CARDS DROP COLUMN created_at, DROP COLUMN updated_at;